CREATE TABLE IF NOT EXISTS project_payment_details (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED NOT NULL,
    method ENUM('easypaisa','jazzcash','bank') NOT NULL,
    account_title VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50) NULL,
    bank_name VARCHAR(255) NULL,
    account_number VARCHAR(100) NULL,
    iban VARCHAR(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_project_payment_details (project_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_payments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT UNSIGNED NOT NULL,
    employer_id BIGINT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    method ENUM('easypaisa','jazzcash','bank') NOT NULL,
    bank_name VARCHAR(255) NULL,
    account_title VARCHAR(255) NULL,
    account_number VARCHAR(100) NULL,
    iban VARCHAR(100) NULL,
    phone_number VARCHAR(50) NULL,
    transaction_reference VARCHAR(255) NOT NULL,
    receipt_path VARCHAR(500) NOT NULL,
    receipt_original_name VARCHAR(255) NULL,
    note TEXT NULL,
    status ENUM('submitted','confirmed','disputed') DEFAULT 'submitted',
    dispute_note TEXT NULL,
    submitted_at TIMESTAMP NULL,
    confirmed_at TIMESTAMP NULL,
    disputed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_project_payments_project (project_id),
    INDEX idx_project_payments_student (student_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (employer_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE
);
